import PDFDocument from 'pdfkit'

export const generatePDF = async (data) => {
    return new Promise((resolve,reject) => {
        const doc = new PDFDocument({
            size:"A4",
            margin:50,
            info:{
                Author:"AvniLLm",
                Title:data.title,
                Creator:"AvniLLm"
            }
        })


        const chunks = []

        doc.on("data",(chunk) => chunks.push(chunk))

        doc.on("end",() => resolve(Buffer.concat(chunks)))

        doc.on("error",reject)
        
        // title
        doc
            .fillColor('#111827')
            .fontSize(28)
            .text(data.title,{
                align:'center'
            })
        
        if(data.subtitle){
            doc.moveDown(0.5)
        

        // sub-title
        doc
            .fillColor('#6B7280')
            .fontSize(12)
            .text(data.subtitle,{
                align:'center'
            })

        doc.moveDown(2)
        
        }

        // sections

        data?.sections?.forEach(s => {
        doc
            .fontSize(18)
            .text(s.heading)
            .fillColor('#111827')

        doc.moveDown(0.5)
            
        s?.points?.forEach((p) => {
            doc
                .fontSize(12)
                .text( "• " + p,{
                    lineGap:5
                })
                .fillColor('#374151')
        })

        doc.moveDown()
        });

        // footer
        doc.moveDown()

        doc
            .fillColor('#9CA3AF')
            .fontSize(10)
            .text("Generated By AvniLLM",{
                align:"center"
            })
        
        doc.end()
    })
}